"""
intent/intent_types.py
======================
The canonical Intent enum. Names are the frozen identifiers from
AURA_COMMAND_SPEC.md Section 22 (Master Intent Table) - never rename.
"""
from __future__ import annotations

from enum import Enum


class Intent(str, Enum):
    """Every intent AURA understands. Value == name for easy serialisation."""
    # Greeting
    GREET = "GREET"
    GREET_MORNING = "GREET_MORNING"
    GREET_NIGHT = "GREET_NIGHT"
    GREET_RETURN = "GREET_RETURN"
    # Assistant
    START_ASSISTANT = "START_ASSISTANT"
    GET_WEATHER = "GET_WEATHER"
    SET_TIMER = "SET_TIMER"
    SET_REMINDER = "SET_REMINDER"
    CALCULATE = "CALCULATE"
    GET_CALENDAR = "GET_CALENDAR"
    CONTROL_MUSIC = "CONTROL_MUSIC"
    WEB_SEARCH = "WEB_SEARCH"
    # Focus
    START_FOCUS = "START_FOCUS"
    SET_FOCUS_DURATION = "SET_FOCUS_DURATION"
    PAUSE_FOCUS = "PAUSE_FOCUS"
    RESUME_FOCUS = "RESUME_FOCUS"
    START_BREAK = "START_BREAK"
    STOP_FOCUS = "STOP_FOCUS"
    FOCUS_STATUS = "FOCUS_STATUS"
    # Translation
    START_TRANSLATION = "START_TRANSLATION"
    TRANSLATE_UTTERANCE = "TRANSLATE_UTTERANCE"
    SET_TRANSLATION_LANGUAGE = "SET_TRANSLATION_LANGUAGE"
    SET_AUTODETECT_LANGUAGE = "SET_AUTODETECT_LANGUAGE"
    PAUSE_TRANSLATION = "PAUSE_TRANSLATION"
    RESUME_TRANSLATION = "RESUME_TRANSLATION"
    STOP_TRANSLATION = "STOP_TRANSLATION"
    # Teacher
    START_TEACHING = "START_TEACHING"
    EXPLAIN = "EXPLAIN"
    SIMPLIFY = "SIMPLIFY"
    GIVE_EXAMPLES = "GIVE_EXAMPLES"
    TEACHER_ASK = "TEACHER_ASK"
    TEACHER_CONTINUE = "TEACHER_CONTINUE"
    TEACHER_REPEAT = "TEACHER_REPEAT"
    TEACHER_SUMMARIZE = "TEACHER_SUMMARIZE"
    STOP_TEACHING = "STOP_TEACHING"
    # Homework
    START_HOMEWORK = "START_HOMEWORK"
    HOMEWORK_HELP = "HOMEWORK_HELP"
    CHECK_ANSWER = "CHECK_ANSWER"
    EXPLAIN_STEPS = "EXPLAIN_STEPS"
    ALT_SOLUTION = "ALT_SOLUTION"
    STOP_HOMEWORK = "STOP_HOMEWORK"
    # Quiz
    START_QUIZ = "START_QUIZ"
    QUIZ_ANSWER = "QUIZ_ANSWER"
    QUIZ_NEXT = "QUIZ_NEXT"
    QUIZ_HINT = "QUIZ_HINT"
    QUIZ_REPEAT = "QUIZ_REPEAT"
    QUIZ_SCORE = "QUIZ_SCORE"
    END_QUIZ = "END_QUIZ"
    # Presentation
    START_PRESENTATION = "START_PRESENTATION"
    SLIDE_NEXT = "SLIDE_NEXT"
    SLIDE_PREV = "SLIDE_PREV"
    PRESENTATION_TIMER = "PRESENTATION_TIMER"
    STOP_PRESENTATION = "STOP_PRESENTATION"
    # Memory
    MEMORY_REMEMBER = "MEMORY_REMEMBER"
    MEMORY_FORGET = "MEMORY_FORGET"
    MEMORY_RECALL = "MEMORY_RECALL"
    STUDY_HISTORY = "STUDY_HISTORY"
    WEAK_SUBJECTS = "WEAK_SUBJECTS"
    ACHIEVEMENTS = "ACHIEVEMENTS"
    DAILY_PROGRESS = "DAILY_PROGRESS"
    # Social
    SOCIAL_THANKS = "SOCIAL_THANKS"
    SOCIAL_HOWAREYOU = "SOCIAL_HOWAREYOU"
    SOCIAL_JOKE = "SOCIAL_JOKE"
    SOCIAL_IDENTITY = "SOCIAL_IDENTITY"
    SOCIAL_COMPLIMENT = "SOCIAL_COMPLIMENT"
    SOCIAL_INSULT = "SOCIAL_INSULT"
    SOCIAL_TIRED = "SOCIAL_TIRED"
    SOCIAL_STRESSED = "SOCIAL_STRESSED"
    SOCIAL_BORED = "SOCIAL_BORED"
    SOCIAL_MOTIVATE = "SOCIAL_MOTIVATE"
    # Robot controls
    LOOK_AT_USER = "LOOK_AT_USER"
    FOLLOW_USER = "FOLLOW_USER"
    STOP_FOLLOW = "STOP_FOLLOW"
    SEARCH_LOOK = "SEARCH_LOOK"
    FACE_GESTURE = "FACE_GESTURE"
    MUTE_SPEECH = "MUTE_SPEECH"
    VOLUME_UP = "VOLUME_UP"
    VOLUME_DOWN = "VOLUME_DOWN"
    WAKE = "WAKE"
    # System
    ENTER_NIGHT = "ENTER_NIGHT"
    WAKE_SYSTEM = "WAKE_SYSTEM"
    SHUTDOWN = "SHUTDOWN"
    RESTART = "RESTART"
    CANCEL = "CANCEL"
    ENTER_NORMAL = "ENTER_NORMAL"
    ENTER_MAINTENANCE = "ENTER_MAINTENANCE"
    HELP = "HELP"
    # Battery
    BATTERY_STATUS = "BATTERY_STATUS"
    # Developer
    DEV_DEBUG = "DEV_DEBUG"
    DEV_STATE = "DEV_STATE"
    DEV_VERSION = "DEV_VERSION"
    # Fallback
    UNKNOWN = "UNKNOWN"
